from flask_sqlalchemy import SQLAlchemy

db = SQLAlchemy()

# Sua tabela Contas a Pagar (e as próximas, uma embaixo da outra)
class ContasAPagar(db.Model):
    __tablename__ = 'contas_a_pagar'
    codigo = db.Column(db.Integer, primary_key=True, autoincrement=True)
    vencimento = db.Column(db.String)
    fornecedor = db.Column(db.String)
    banco_pagamento = db.Column(db.String)
    valor = db.Column(db.Float)
    valor_pago = db.Column(db.Float)
    valor_pendente = db.Column(db.Float)
    documento = db.Column(db.String)
    documento_tipo = db.Column(db.String)
    pagamento_tipo = db.Column(db.String)
    plano_de_contas = db.Column(db.String)
    data_cadastro = db.Column(db.String)
    comentario = db.Column(db.String)
    empresa = db.Column(db.String)
    conta = db.Column(db.String)
    status = db.Column(db.String)
    categorias = db.Column(db.String)
    tipo_custo = db.Column(db.String)
    centro_de_custo = db.Column(db.String)
    tipo = db.Column(db.String)
    data_pagamento = db.Column(db.String)
    arquivo_pagamento = db.Column(db.String)
    arquivo_documento = db.Column(db.String)
    arquivo_xml = db.Column(db.String)
    arquivo_boleto = db.Column(db.String)
    agendamento = db.Column(db.String)
    nome___raz_o_social = db.Column(db.String)
    banco_previsto = db.Column(db.String)
    tipo_documento = db.Column(db.String)
    tipo_pagamento = db.Column(db.String)
    data_competencia = db.Column(db.String)
    data_documento = db.Column(db.String)
    recebimento = db.Column(db.String)
    codigo_externo = db.Column(db.String)
    editado_local = db.Column(db.String, default='0')
